name: Update GitHub Metrics Anilist

on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: prod
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          template: classic
          filename: assets/gen/metrics-anilist.svg
          config_display: large
          token: NOT_NEEDED
          base: ""

          plugin_anilist: yes
          plugin_anilist_user: abdxdev
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites
          plugin_anilist_limit: 2
